In [2]:
print('Testas')

Testas


In [3]:
# klases
s = 'tekstas'
sk = 7
sar = []
print(type(s), type(sk), type(sar), sep= '\n')
s.upper()

<class 'str'>
<class 'int'>
<class 'list'>


'TEKSTAS'

In [4]:
def calculateAge():
  return 'Cha!!!'


class Asmuo():
  def __init__(self, name, gm):
    self.Name = name # klases atributas (tiesiog kintamasis, esantis klases viduje)
    self.BYear = gm
    self.Age = self.calculateAge() #kaip kreiptis i metoda is kito metodo
    pass
  
  def getname(self):
      return self.Name
  
  def setName(self, new_name):
    self.Name = new_name
    
  def calculateAge(self):
    return 2024-self.BYear
    
  

In [5]:
a1 = Asmuo('Vardenis', 1996)
print(a1.Age, a1.getname())

28 Vardenis


In [6]:
# paveldejimas

class Studentas(Asmuo):
  def getStatus(self):
    return 'Studentas'



In [7]:
std1 = Studentas('une', 1992)

In [8]:
print(std1.Age, std1.getname())

32 une


In [9]:
std1.getStatus()

'Studentas'

In [10]:
# sudetingesnis paveldijimo atvejis

class Studentas(Asmuo):
  def __init__(self, name , gm):
    super().__init__(name, gm)
    self.Enroll = True
    
std1 = Studentas('une', 1996)


In [11]:
print(std1.Age, std1.Enroll)

28 True


In [12]:
# aprašykite klasę Kvadratas
# kreipiantis į klasę, reikia nurodyti kvadrato ilgį a.
# Klasė turi turėti atributą Plotas, kurį 
# turi apskaičiuoti klasės kūrimo metu.
# Plotas = a*a
# parašykite metodą, kuris grąžintų apskaičiuoto Plotas atributo reikšmę.

class Kvadratas():
  def __init__(self, a):
    self.Plotas = a*a   
    pass  
  def plotas(self):
    return self.Plotas
  
Kvadratu = Kvadratas(a=6)
print(Kvadratu.plotas())



36


In [13]:
# aprašykite klasę Rectangle
# kreipiantis į klasę, reikia nurodyti stačiakampio
# kraštines a ir b.
# Realizuokite atributą Plotas = a*b
# ir metodą, grąžinantį Ploto reikšmę
# Taip pat pridėkite metodą, apskaičiuojantį ir grąžinantį
# perimetrą P=2(a+b)

class Rectangle():
  def __init__(self, a, b):
    self.Plotas = a*b
    self.Perimetras = 2*(a+b)
    
    pass
    
  def Staciakampis(self):
    return self.Plotas
  
  def perimetru(self):
    return self.Perimetras

perimetras = Rectangle(a=12,b=13)
staciakampis = Rectangle(a=12,b=13)
print(staciakampis.Staciakampis())
print(perimetras.perimetru())
    

156
50


In [14]:
class Kubas(Rectangle):
  def __init__(self, a, b, c):
    super().__init__(a, b,)
    self.Kubas = a*b*c
  def kubas(self):
    return self.Kubas
  
perimetras = Rectangle(a=12,b=13)
staciakampis = Rectangle(a=12,b=13)
Kubikas = Kubas(a=12,b=13,c=14)
print(staciakampis.Staciakampis())
print(perimetras.perimetru())
print(Kubikas.kubas())
    

156
50
2184


In [15]:
#susikurkite su Notepadu tekstinį failą su bet kokiu tekstu
#parašykite klasę TxtReader, kuriai kreipimosimetu būtų nurodomas tekstinio failo pavadinimas;
#klasės sukūrimo metu tas tekstinis failas turi būti nuskaitomas
#ir nuskaitytas tekstas turi būti priskirtas atributui Text
#parašykite metodą getText(), kuri grąžintų atributo text reikšmę\

class TxtReader:
    def __init__(self, filename):
        self.text = ""
        with open(filename, 'r') as file:
            self.text = file.read()
            

    def getText(self):
        return self.text

reader = TxtReader("xdd.txt")
text = reader.getText()
print(text)

Laba diena


In [16]:
#parašykite klasę TxtAnalyzer, 
# kuriai kreipimosi metu galima būtų nurodyti failo pavadinimą ir stulpelių skirtuką.
#klasė sukūrimo metu turi nuskaityti failą, 
# stulpelius skaičių suskirstyti į sąrašus ir juos priskirti atributams X, Y ir Z.
#Realizuokite metodus, kurie grąžintų X, Y, Z sąrašų vidurkius, 
# minimalias ir maksimalias vertes. Pythone yra min, max, sum funkcijos;

class TxtAnalyzer: 
  def __init__(self, file_name, delimiter): 
    self.X = [] 
    self.Y = [] 
    self.Z = []
    
    with open(file_name, 'r') as file:
        for line in file:
            columns = line.strip().split(delimiter)
            self.X.append(float(columns[0]))
            self.Y.append(float(columns[1]))
            self.Z.append(float(columns[2]))

def get_average(self, attribute):
    if attribute == 'X':
        return sum(self.X) / len(self.X)
    elif attribute == 'Y':
        return sum(self.Y) / len(self.Y)
    elif attribute == 'Z':
        return sum(self.Z) / len(self.Z)

def get_min(self, attribute):
    if attribute == 'X':
        return min(self.X)
    elif attribute == 'Y':
        return min(self.Y)
    elif attribute == 'Z':
        return min(self.Z)

def get_max(self, attribute):
    if attribute == 'X':
        return max(self.X)
    elif attribute == 'Y':
        return max(self.Y)
    elif attribute == 'Z':
        return max(self.Z)
  
analyzer = TxtAnalyzer('data2.txt', ',') 
print(analyzer.get_average('X')) 
print(analyzer.get_min('Y')) 
print(analyzer.get_max('Z'))

ValueError: could not convert string to float: '86;0'

In [ ]:
#Sukurkite klasę Rutulys
#kuriai galėtumėte nurodyti Rutulio spindulį r.
#Sukurkite metodus, skirtus rasti jo Tūriui ir paviršiaus plotui;
#Taip pat metodą, kuriuo jūs pakeistumėte spindulio r reikšmę.

class Rutulys: 
  def __init__(self, spindulys): 
    self.spindulys = spindulys
  def skaiciuoti_turi(self):
    return (4/3) * 3.14 * self.spindulys ** 3

def skaiciuoti_ploti(self):
    return 4 * 3.14 * self.spindulys ** 2

def pakeisti_spindulio_reiksme(self, naujas_spindulys):
    self.spindulys = naujas_spindulys
    
rutulys = Rutulys(5) 
print("Tūris:", rutulys.skaiciuoti_turi()) 
print("Paviršiaus plotas:", rutulys.skaiciuoti_ploti())

rutulys.pakeisti_spindulio_reiksme(7) 
print("Po spindulio pakeitimo:") 
print("Tūris:", rutulys.skaiciuoti_turi()) 
print("Paviršiaus plotas:", rutulys.skaiciuoti_ploti())

Tūris: 523.3333333333334


AttributeError: 'Rutulys' object has no attribute 'skaiciuoti_ploti'

In [ ]:
#Sukurkite klasę Rutulys
#kuriai galėtumėte nurodyti Rutulio spindulį r.
#Sukurkite metodus, skirtus rasti jo Tūriui ir paviršiaus plotui;
#Taip pat metodą, kuriuo jūs pakeistumėte spindulio r reikšmę.

class Rutulys():
    def __init__ (self, r):
        self.r = r
           
    def getPav_Plotas(self):
        Pav_Plotas = 4*3.14*self.r**2
        return Pav_Plotas

    def getTūris(self):
        Tūris = 4/3*3.14*self.r**3
        return Tūris
    
    def changer(self, new_r):
        self.r = new_r
        
r = int(input("Įveskite spindulį r"))
    
rutulys  = Rutulys(r)
print(rutulys.getPav_Plotas())
print(rutulys.getTūris())

r = int(input("Įveskite spindulį r"))
rutulys.changer(r)

print(rutulys.getPav_Plotas())
print(rutulys.getTūris())

2826.0
14130.0
7234.56
57876.479999999996


In [ ]:
class Rectangle():

    def __init__(self, a, b): 

        self.S = a * b

        self.P = 2*(a + b)

    def getP(self):      

        return self.P

    def getS(self):      

        return self.S

figura = Rectangle(a=10, b=5)

print("Plotas: ", figura.getS(), "Perimetras: ",figura.getP(), sep= '/n') 
 
 
class Piramide(Rectangle):

    def __init__ (self, a, b, h):

        super().__init__(a, b) # cia atkeliavo is Rectangle funkcijos, 9 eilute

        self.h = h

    def get_piramides_turis(self):

        Turis = 1/3*self.S*self.h

        return Turis

figura = Piramide(a= 2, b=3, h=5)

print("Piramides turis: ", figura.get_piramides_turis())

class Kubas(Rectangle):

    def __init__ (self, a, b, h):

        super().__init__(a, b) # cia atkeliavo is Rectangle funkcijos, 9 eilute

        self.a = h

    def getKubo_turis(self):

        Turis = self.S*self.a

        return Turis

figura = Kubas(a= 2, b=5, h= 3)

print("Kubo turis: ", figura.getKubo_turis())

Plotas: /n50/nPerimetras: /n30
Piramides turis:  10.0
Kubo turis:  30


In [ ]:
#parašykite klasę TxtAnalyzer, kuriai kreipimosi metu galima būtų nurodyti failo pavadinimą ir stulpelių skirtuką.
#klasė sukūrimo metu turi nuskaityti failą, stulpelius skaičių suskirstyti į sąrašus ir juos priskirti atributams X, Y ir Z.
#Realizuokite metodus, kurie grąžintų X, Y, Z sąrašų vidurkius, minimalias ir maksimalias vertes. Pythone yra min, max, sum funkcijos


class TxtAnalyzer():
    def __init__(self, pav, skirtukas):
        self.pavadinimas = pav
        self.skirt = skirtukas
        self.x = []
        self.y = []
        self.z = []
        pass
    def TxtReader(self):
        fname = self.pavadinimas
        f = open(fname, mode='r', encoding='utf-8')
        tekstas = f.readlines()
        print(tekstas)
        f.close()
        for x in tekstas:
            self.x.append(float(x.split(self.skirt)[0]))
            self.y.append(float(x.split(self.skirt)[1]))
            self.z.append(float(x.split(self.skirt)[2]))
        print(self.x)
        print(self.y)
        print(self.z)
    def Getvidurkis(self):
      vidurkisX = sum(self.x)/len(self.x)
      vidurkisY = sum(self.y)/len(self.y)
      vidurkisZ = sum(self.z)/len(self.z)
      
      return vidurkisX, vidurkisY, vidurkisX
    
    def getMinimali(self):
      minimaliX = min(self.x)
      minimaliY = min(self.y)
      minimaliZ = min(self.z)
      return minimaliX, minimaliY, minimaliX
      
    def getMax(self):
      minimaliX = max(self.x)
      minimaliY = max(self.y)
      minimaliZ = max(self.z)
      return minimaliX, minimaliY, minimaliX



z = TxtAnalyzer('data1.txt',';')
z.TxtReader()
print(z.Getvidurkis())
print(z.getMinimali())
print(z.getMax())

['86;0.0861;7.4004\n', '72;0.6167;44.4012\n', '89;0.7936;70.6346\n', '46;0.9893;45.5059\n', '6;0.2072;1.2433\n', '11;0.311;3.4213\n', '94;0.0604;5.6772\n', '77;0.6974;53.7036\n', '73;0.1612;11.7683\n', '57;0.8905;50.7593\n', '75;0.9656;72.4181\n', '82;0.8679;71.1689\n', '98;0.9158;89.7523\n', '3;0.8417;2.525\n', '71;0.0056;0.3983\n', '37;0.9722;35.9721\n', '61;0.2773;16.9152\n', '61;0.5739;35.0072\n', '57;0.2564;14.6146\n', '58;0.0542;3.1412\n', '44;0.866;38.1054\n', '45;0.4577;20.5961\n', '87;0.6506;56.601\n', '17;0.1213;2.0614\n', '53;0.5227;27.701\n', '16;0.5716;9.1453\n', '11;0.2818;3.1001\n', '3;0.1833;0.5498\n', '21;0.7497;15.7429\n', '62;0.3648;22.6154\n', '68;0.6545;44.5043\n', '50;0.9699;48.4964\n', '17;0.3595;6.1108\n', '27;0.2759;7.4481\n', '48;0.3391;16.2765\n', '64;0.5959;38.1344\n', '87;0.3402;29.5946\n', '61;0.8638;52.6946\n', '21;0.5741;12.0552\n', '55;0.366;20.1273\n', '50;0.334;16.7012\n', '59;0.9611;56.7033\n', '29;0.7874;22.8354\n', '15;0.5987;8.9802\n', '72;0.8562;

In [ ]:
class TxtAnalyzer:
    def __init__(self, fileName, dell=';'):
        self.fileName = fileName
        self.dell = dell
        self.X, self.Y, self.Z = self.readFile()
    def readFile(self):
        X, Y, Z = [], [], []
        try:
             with open(self.fileName, 'r') as file:
                for line in file:
                    values = line.strip().split(self.dell)
                    if len(values) == 3:
                        X.append(float(values[0]))
                        Y.append(float(values[1]))
                        Z.append(float(values[2]))
        except FileNotFoundError:
            print("File not found!")
        return X, Y, Z
    def Ave(self, data):
        if data:
            return sum(data)/len(data)
        else:
            return None
    def Min(self, data):
        if data:
            return min(data)
        else:
            return None
    def Max(self, data):
        if data:
            return max(data)
        else:
            return None
fileName = "data1.txt"  
analyzer = TxtAnalyzer(fileName)
print("X: ")
print("Ave:", analyzer.Ave(analyzer.X))
print("Min:", analyzer.Min(analyzer.X))
print("Max:", analyzer.Max(analyzer.X))
print("\nY: ")
print("Ave:", analyzer.Ave(analyzer.Y))
print("Min:", analyzer.Min(analyzer.Y))
print("Max:", analyzer.Max(analyzer.Y))
print("\nZ: ")
print("Ave:", analyzer.Ave(analyzer.Z))
print("Min:", analyzer.Min(analyzer.Z))
print("Max:", analyzer.Max(analyzer.Z))

X: 
Ave: 52.76
Min: 3.0
Max: 98.0

Y: 
Ave: 0.534946
Min: 0.0056
Max: 0.9893

Z: 
Ave: 27.449029
Min: 0.3983
Max: 89.7523


In [17]:
x = [1,2,3,4,5]

naujas_x = []
for skaicius in x:
  naujas_x.append(skaicius - 0.75)
print(naujas_x)
  

[0.25, 1.25, 2.25, 3.25, 4.25]


In [1]:
import numpy as np

In [13]:
# array
x = np.arange(0,10)
print(x)
print(type(x))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [14]:
# array
x = np.arange(0,10,2) # kas antra skaiciu
print(x)
print(type(x))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [15]:
y = x - 0.75
print(y)

[-0.75  1.25  3.25  5.25  7.25]


In [18]:
np.average()
np.min()
np.mean() # vidurkis
np.median()

TypeError: min() missing 1 required positional argument: 'a'

In [19]:
a_list = [i for i in range(1,11)]
print(a_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [21]:
a_array = np.asarray(a_list)
print(a_array+0.75)

[ 1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75]


In [27]:
x = [1,2,3]
y = [1,4,5]
x_np = np.asarray(x)
y_np = np.asarray(y)
c = x_np*y_np
print(c)

[ 1  8 15]


In [ ]:
np.min(x)
np.max(y_np)

In [29]:
atsitiktinis=np.random.randint(0,10,100) # patys nurodom ribas kokius skaicius generuoti
print(atsitiktinis)

[7 4 0 7 9 3 8 7 4 5 9 8 1 1 8 0 0 1 8 3 9 7 7 3 8 6 0 9 2 7 2 7 4 9 8 0 7
 1 8 0 7 2 7 0 2 5 2 6 4 6 3 3 8 0 1 6 9 3 3 3 4 3 9 9 2 7 2 5 6 6 5 4 5 0
 2 4 8 6 7 8 5 4 0 3 2 1 9 2 6 4 5 4 7 6 0 3 1 6 6 4]


In [31]:
atsitiktinis_float = np.random.rand(100) #0-1 tik skaicius
print(atsitiktinis_float)

[0.81130766 0.43586636 0.49640549 0.97928232 0.59715507 0.33463867
 0.27962216 0.52228272 0.73643704 0.65498538 0.97196581 0.20608719
 0.71668739 0.75166138 0.1987136  0.4736748  0.57579684 0.12991291
 0.9358751  0.13735177 0.95626871 0.92007274 0.08796714 0.26784784
 0.3859453  0.24570411 0.66218231 0.37941876 0.13840522 0.34122315
 0.07340406 0.26258969 0.56716274 0.2880725  0.1286532  0.99868519
 0.84953142 0.53749411 0.05396732 0.63723016 0.38200099 0.82133032
 0.19879407 0.28455009 0.95638941 0.29858626 0.91799437 0.17004133
 0.21195074 0.75662121 0.73220808 0.5463925  0.49775268 0.66072938
 0.3387616  0.73450816 0.35518224 0.04469091 0.3307817  0.4235737
 0.79777327 0.20612924 0.53391781 0.70747891 0.87759645 0.87376144
 0.30656566 0.73599704 0.85218418 0.15767714 0.34619088 0.95583215
 0.10159915 0.09905372 0.51046309 0.56686873 0.77878661 0.73763801
 0.5368396  0.87804466 0.68255669 0.61975659 0.91148475 0.89211892
 0.30250758 0.67487959 0.74790901 0.93090569 0.13600543 0.67168

In [39]:
xas = np.random.randint(1,10,100)
svoriai = np.random.rand(100)
#mean ir average
vidurkis = np.mean(xas)
print(vidurkis)
sv_vid = np.average(xas)
print(sv_vid)


4.87
4.87


In [38]:
xas = np.random.randint(1,10,100)
svoriai = np.random.rand(100)
#mean ir average
vidurkis = np.mean(xas)
print(vidurkis)
sv_vid = np.average(xas, weights=svoriai)
print(sv_vid)

5.01
4.9038813262229


In [40]:
xas = np.random.randint(1,10,100)
svoriai = np.random.rand(100)
#mean ir average
vidurkis = np.mean(xas)
print(vidurkis)
sv_vid = np.average(xas, weights=svoriai)
print(sv_vid)
#median()
medx= np.median(xas)
print(medx)

5.29
5.1714378486403625
6.0


In [41]:
xas = np.random.randint(1,10,100)
svoriai = np.random.rand(100)
#mean ir average
vidurkis = np.mean(xas)
print(vidurkis)
sv_vid = np.average(xas, weights=svoriai)
print(sv_vid)
#median()
medx= np.median(xas)
print(medx, np.min(xas), np.max(xas))

5.06
5.256578532274551
6.0 1 9


In [53]:
l = np.linspace(1,10,15)
print(l)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [50]:
l = np.linspace(1,10,10, endpoint=False)
print(l)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [57]:
# asarray, arange, min, max,mean ,average,median
n_np = np.arange(0,10)
#kaip metodai:
minn = n_np.min()
print(minn)
print(n_np.mean())
print(n_np.max())

0
4.5
9


In [80]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [111]:
%autoreload 2
import modulis

In [86]:
print(modulis.A)

60


In [87]:
modulis.printA()

As esu printA() xdd funkcijaxdd


In [91]:
# iškelkite savo anksčiau rašytas Vehicle, Car, etc klases
# į modulį
# ir patikrinkite klasių veikimą
# sukurdami kintamuosius ir patikrindami jų veikimą

import Vehicle


SyntaxError: invalid syntax (48948273.py, line 6)

In [113]:
test = modulis.Car(P='pavadinimas',R=5000,S=4)

print(test.GetSeats())
test = modulis.Bus(P='pavadinimas',R=5000,S=4)

print(test.GetSeats())  
test = modulis.Train(P='pavadinimas',R=5000,S=4)

print(test.GetSeats())

pavadinimasturi 4 sedimu vietu
pavadinimasturi 4 sedimu vietu
pavadinimasturi 4 sedimu vietu


In [115]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti
class keturiolika_failu():
    def __init__(self, Pavadinimas, Skirtukas):
        self.Pavadinimas = Pavadinimas
        self.Skirtukas = Skirtukas
        self.I = []
        self.U = []
        self.j = []
        self.p = []
    def dataReader(self):
        fname = self.Pavadinimas
        file = open(fname, mode='r', encoding= 'utf-8')
        sarasas = file.readlines() # suformuoja teksta kaip eiluciu sarasa
        file.close()
        print(sarasas) # pasitikrinam ar veikia
        for eilute in sarasas[1::]:
            self.I.append(float(eilute.split(self.Skirtukas)[0]))
            self.U.append(float(eilute.split(self.Skirtukas)[1]))           
            self.j.append(float(eilute.split(self.Skirtukas)[2]))
            self.p.append(float(eilute.split(self.Skirtukas)[3].replace('\n', '')))
        print(self.I)
        print(self.U) 
        print(self.j) 
        print(self.p) 
    def getPmax(self):
        Pmax = (max(self.p))
        return Pmax
    
    def getPCE(self):
        Pmax= self.getPmax()
        PCE = round((Pmax / 1000 * 100),2)
        return PCE
    
sarasas = keturiolika_failu('REF_D_5k_FW_2.03.dat', ';') #pasitikrinam ar nuskaito info is failo
sarasas.dataReader()
print(sarasas.getPCE())




['U[V] ; I[A] ; j[mA/cm^2] ; P[mW/cm^2]\n', '1.2 ; 0.0010878 ; 13.59755 ; 16.31706\n', '1.1766667 ; 0.0008779 ; 10.9735512 ; 12.912212\n', '1.1533333 ; 0.000675 ; 8.4376562 ; 9.7314302\n', '1.13 ; 0.0004624 ; 5.780055 ; 6.5314621\n', '1.1066667 ; 0.0002595 ; 3.2442637 ; 3.5903185\n', '1.0833333 ; 7.83e-05 ; 0.9787641 ; 1.0603278\n', '1.06 ; -7.92e-05 ; -0.9902056 ; -1.049618\n', '1.0366667 ; -0.0002111 ; -2.63856 ; -2.7353072\n', '1.0133333 ; -0.0003275 ; -4.0936325 ; -4.1482143\n', '0.99 ; -0.0004257 ; -5.3214875 ; -5.2682726\n', '0.9666667 ; -0.0005053 ; -6.3163262 ; -6.105782\n', '0.9433333 ; -0.0005775 ; -7.2184413 ; -6.8093962\n', '0.92 ; -0.0006322 ; -7.9018762 ; -7.2697261\n', '0.8966667 ; -0.0006841 ; -8.55161 ; -7.6679436\n', '0.8733333 ; -0.0007236 ; -9.0446012 ; -7.8989518\n', '0.85 ; -0.0007626 ; -9.5324562 ; -8.1025878\n', '0.8266667 ; -0.0007935 ; -9.9188812 ; -8.1996085\n', '0.8033333 ; -0.00082 ; -10.2496088 ; -8.2338524\n', '0.78 ; -0.000844 ; -10.54984 ; -8.2288752\n'

In [7]:
# Sukurkite Mokinys klasę, kuri turės mokinio vardą, pavardę ir sąrašą pažymių. Įtraukite metodus,
# kurie skaičiuotų vidurkį, didžiausią ir mažiausią pažymį.

# Sukurkite Abiturientas klasę, kuri paveldi Mokinys klasę ir prideda papildomą funkcionalumą, pvz.,
# gebėjimą pridėti egzamino rezultatus ir skaičiuoti bendrą vidurkį, įskaitant ir egzamino rezultatus.

# Sukurkite Mokykla klasę, kuri turės sąrašą Mokinys objektų. Įtraukite metodus, kurie leistų pridėti
# naują mokinį, pašalinti mokinį, bei skaičiuoti visos mokyklos mokinių pažymių vidurkius.

# Atnaujinkite Mokinys klasę taip, kad pažymių sąrašas būtų privatus. Sukurkite metodus, kurie
# leistų saugiai pridėti ir gauti pažymius, užtikrinant, kad negalima būtų pridėti netinkamų pažymių
# (pvz., neigiamų ar didesnių nei 10).

# Klasės turi būti aprašytos jūsų kuriamame modulyje.
# Klases tikrinimui importuokite taip, kad 
# NEREIKĖTŲ modulio pavadinimo prieš klasę naudoti.


class Mokinys: 
  def __init__(self, vardas, pavarde, pazymiai): 
    self.vardas = vardas 
    self.pavarde = pavarde 
    self.__pazymiai = pazymiai
  def vidurkis(self):
    return sum(self.__pazymiai) / len(self.__pazymiai)

  def didziausias_pazymys(self):
    return max(self.__pazymiai)

  def maziausias_pazymys(self):
    return min(self.__pazymiai)
  
class Abiturientas(Mokinys): 
  def __init__(self, vardas, pavarde, pazymiai, egzaminas): 
    super().__init__(vardas, pavarde, pazymiai) 
    self.egzaminas = egzaminas
    self.pazymiai = pazymiai
  def bendras_vidurkis(self):
    bendras_pazymiai = self.pazymiai + [self.egzaminas]
    return sum(bendras_pazymiai) / len(bendras_pazymiai) 
  
class Mokykla: 
  def __init__(self): 
    self.mokiniai = [] 
  def prideti_mokini(self, mokinys):
    self.mokiniai.append(mokinys)

  def pasalinti_mokini(self, mokinys):
    self.mokiniai.remove(mokinys)

  def visu_vidurkiai(self):
    return [mokinys.vidurkis() for mokinys in self.mokiniai]
  
m1 = Mokinys('Jonas', 'Jonaitis', [8, 9, 7]) 
print(m1.vidurkis()) 
print(m1.didziausias_pazymys()) 
print(m1.maziausias_pazymys())

a1 = Abiturientas('Petras', 'Petraitis', [8,6,7], 9) 
print(a1.bendras_vidurkis())

m2 = Mokinys('Ona', 'Onaite', [9, 10, 10]) 
m3 = Mokinys('Antanas', 'Antanaitis', [7, 8, 6])

mokykla = Mokykla() 
mokykla.prideti_mokini(m1) 
mokykla.prideti_mokini(m2) 
mokykla.prideti_mokini(m3)

print(mokykla.visu_vidurkiai())  

8.0
9
7
7.5
[8.0, 9.666666666666666, 7.0]


In [9]:
import pandas